export { addDependencies } from './addDependencies/addDependencies'
export { registerOperation } from './registerOperation/registerOperation'
export { configureProject } from './configureProject/configureProject'
export { configureTypedoc } from './configureTypedoc/configureTypedoc'
export { configureGitIgnore } from './configureGitIgnore/configureGitIgnore'
