export type { Predicate, DataType } from './lib/shared/model'
export { setConfig } from './lib/shared/consts'
export { getConfig } from './lib/shared/consts'
export { registerClassTypes } from './lib/registerClassTypes/registerClassTypes'
export { registerIterableClass } from './lib/registerIterableClass/registerIterableClass'
export { deregisterClassTypes } from './lib/deregisterClassTypes/deregisterClassTypes'
export { deregisterIterableClass } from './lib/deregisterIterableClass/deregisterIterableClass'
export { getType } from './lib/getType/getType'
export { sameType } from './lib/sameType/sameType'
export { sameStructure } from './lib/sameStructure/sameStructure'
export { isIterable } from './lib/isIterable/isIterable'
export { hasCircularReference } from './lib/hasCircularReference/hasCircularReference'
export { isIdentical } from './lib/isIdentical/isIdentical'
export { containsKeys } from './lib/containsKeys/containsKeys'
