export { setConfig, getConfig } from '../shared/consts'
export { registerClassTypes } from '../registerClassTypes/registerClassTypes'
export { registerIterableClass } from '../registerIterableClass/registerIterableClass'
export { deregisterClassTypes } from '../deregisterClassTypes/deregisterClassTypes'
export { deregisterIterableClass } from '../deregisterIterableClass/deregisterIterableClass'
