# Sync Projects
#
# This action will scan changes made as part of a pull request,
# merges those changes into the enterprise repository.
#

name: Sync Projects
on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.ENIO_TO_ENTERPRISE_SYNC_PAT }}
